import {assets} from "../../assets/assets";
import "./ChatPanel.css";
import InputBar from "../InputBar/InputBar.jsx";
import {useSelector} from "react-redux";
import ResultCard from "./ResultCard.jsx";


// middle ware will call the setActiveSessionID and set the results in chats
function ChatPanel() {
    const username  = useSelector(state => state.chatPanel.username);
    const chats  = useSelector(state => state.chatPanel.chats);
    const activeSessionId = useSelector(state => state.sideBar.activeSessionId);

    return (
        <div className="main">
            <div className="nav">
                <p>AI Chat</p>
                <img src={assets.user_icon} alt=""/>
            </div>

            <div className="main-container">
                {activeSessionId === null ?
                  <>
                    <div className="greet">
                      <p>
                        <span>Hello, {username}</span>
                      </p>
                      <p>How can I help you today ??</p>
                    </div>
                  </>
                  :
                  <div className="all-results">
                      {chats?.map((item, index) => {
                             return (<ResultCard key={index} input={item.request} resultData={item.response} loading={item.loading} fileName={item.fileName}/>)
                      })}
                  </div>
              }

              <div className="main-bottom">
                <InputBar />
                <p className="bottom-info">
                The content generated by AI may display inaccurate information, so
                        double check its responses.
                    </p>
                </div>
            </div>
        </div>
    );
}

export default ChatPanel;
